apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-api
  template:
    metadata:
      labels:
        app: ticket-api
    spec:
      containers:
      - name: ticket-api
        image: larstechchamps/ticket-shop:1.0.0
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_URL
            value: "postgres://postgres:postgres@ticket-db:5432/tickets"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
