grafana.ini:
  server:
    root_url: http://192.168.178.113:32000
    serve_from_sub_path: false

service:
  type: NodePort
  port: 80
  nodePort: 32000

adminUser: admin
adminPassword: admin

persistence:
  enabled: true
  storageClassName: local-path
  size: 1Gi
