grafana.ini:
  server:
    root_url: http://192.168.178.113:32000
    serve_from_sub_path: false

service:
  type: NodePort
  port: 80
  nodePort: 32000

adminUser: admin
adminPassword: admin

persistence:
  enabled: true
  storageClassName: local-path
  size: 1Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prom-prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: kubernetes
        orgId: 1
        folder: Kubernetes
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/kubernetes

dashboards:
  kubernetes:
    kubernetes-pods:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
    kubernetes-cluster:
      gnetId: 315
      revision: 3
      datasource: Prometheus
