apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ticket-db
spec:
  serviceName: ticket-db
  replicas: 1
  selector:
    matchLabels:
      app: ticket-db
  template:
    metadata:
      labels:
        app: ticket-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "pass"
            - name: POSTGRES_DB
              value: "tickets"
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: ticket-db-init         
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
